### ISSUE TITLE
How to burn to a cd?

### ISSUE THREAD

**Issue by Jyri-K** [filipalac/240pTestSuite-PS1#2]
First: Thank you porting 240p Test Suite to Playstation!
How can I burn this to a CD-R and use with a modded Playstation? Is there some recommended program and burn settings to get this to work? Tried to burn this with cdrtfe but didn't get discs that would work on my PS1.

**Comment by Jyri-K** [comment]
Actually, now that I tested those burned cds on PS1 emulator on PC, they work just fine. Maybe there is something wrong with my PS1's hardware...

**Comment by ramapcsx2** [comment]
You do have a modchip installed, or use another method to start unlicensed disks, right? :)

**Comment by Jyri-K** [comment]
Yes, I have a Game Enhancer which is connected to the back of my PS1. And it works as I can play import games just fine.
![GameEnhancer](http://farm4.static.flickr.com/3017/2446151246_e1d24b247e.jpg)

**Comment by ramapcsx2** [comment]
Okay, well, then I don't know what's wrong. All I can say is that it works fine here. Might be your CD-R?
I use imgburn and just feed it the .cue file.

**Comment by Jyri-K** [comment]
Got the cd to work. I had to adjust the PS1 laser to make it read burned games. Now to adjust the tv :)

**Comment by masonvd27** [comment]
Stupid question: What exactly am I burning to the CD? The entire file folder? I don't see a .cue or .iso or anything like that. Sorry if this question is astoundingly stupid.

**Comment by Jyri-K** [comment]
.bin and .cue files are in the binary folder :)
