### ISSUE TITLE
The image doesn't run in mednafen psx

### ISSUE THREAD

**Issue by vadosnaprimer** [filipalac/240pTestSuite-PS1#7]
Mednafen is [one of the most accurate PS1 emulators](http://emulation.gametechwiki.com/index.php/PS1_Tests), but it doesn't run this test suite. It says there are uncorrectable errors in a bunch of sectors during the BIOS screen. It also falsely auto-detects the image as PAL.

**Comment by ramapcsx2** [comment]
Mednafen is right, the image has been mastered incorrectly. You can try and repair it:
https://server.romhacking.net/utilities/1550/

**Comment by filipalac** [comment]
fixed

**Comment by vadosnaprimer** [comment]
Thanks, it works now!
